// <auto-generated />
namespace eSiroi.Resource.eSiroiResourceMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_remarks_column : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_remarks_column));
        
        string IMigrationMetadata.Id
        {
            get { return "201509040448054_added_remarks_column"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
